cask_args appdir: '~/app/homebrew'

tap 'homebrew/bundle'

brew 'colima'
brew 'docker'
brew 'docker-compose'
brew 'fastfetch'
brew 'flock'
brew 'ffmpeg'
brew 'htop'
brew 'jq'
brew 'mas'
brew 'wget'
brew 'yt-dlp'

cask 'pdfsam-basic'
cask 'cameracontroller'
cask 'cursor'
cask 'miniconda'
cask 'flowvision'
cask 'pearcleaner'
cask 'postman'
cask 'kui'
cask 'ubersicht'
cask 'visual-studio-code'
cask 'vlc'
cask 'vnc-viewer'
cask 'warp'

mas "SrongBox", id: 1615410888
